#!/bin/bash
pwd
press
C-x C-s
ls -a
chmod u+x 0-current_working_directory
git config user.email"marymativo850@gmail.com"
git config user.name"marymativo"
git add .
git commit -m 'working directory'
git push
